//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alarm()
        {
            this.AlarmLogArchives = new HashSet<AlarmLogArchive>();
            this.AlarmResetIds = new HashSet<AlarmResetId>();
            this.AlarmLogs = new HashSet<AlarmLog>();
        }
    
        public int AlarmId { get; set; }
        public string AlarmName { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsResetRequired { get; set; }
        public Nullable<bool> IsCommentRequired { get; set; }
        public Nullable<bool> IsMachineRequiredToStop { get; set; }
        public Nullable<bool> IsCountForReject { get; set; }
        public Nullable<bool> BitValue { get; set; }
        public Nullable<bool> IsCheckAtMachineStart { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> lastvalue { get; set; }
        public Nullable<int> MachineParameterId { get; set; }
        public Nullable<int> MachineStopMachineParameterId { get; set; }
        public Nullable<bool> IsRefreshMachineSettings { get; set; }
        public Nullable<bool> IsHideEdit { get; set; }
        public Nullable<bool> IsAlarmForCounter { get; set; }
        public string RecordAddedSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmLogArchive> AlarmLogArchives { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual MachineParameter MachineParameter { get; set; }
        public virtual MachineParameter MachineParameter1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmResetId> AlarmResetIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmLog> AlarmLogs { get; set; }
    }
}
