//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmLog
    {
        public long AlarmLogId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> AlarmId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> LoggedUserId { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AlarmDateTime { get; set; }
        public string PCIPAddress { get; set; }
        public Nullable<bool> IsAlarmActive { get; set; }
    
        public virtual Alarm Alarm { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual User User { get; set; }
    }
}
