//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogArchive
    {
        public long AuditLogArchiveId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RowId { get; set; }
        public string Module { get; set; }
        public string Page { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Comments { get; set; }
        public string PCIPAddress { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string BatchName { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> PickListValueId { get; set; }
        public Nullable<int> AuthenticationId { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual PickListValue PickListValue { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
