//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchRecipeModify
    {
        public int BatchRecipeModifyId { get; set; }
        public Nullable<int> BatchMachineId { get; set; }
        public Nullable<int> RecipeSettingsParameterId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual BatchMachineWise BatchMachineWise { get; set; }
        public virtual RecipeSettingsParameter RecipeSettingsParameter { get; set; }
        public virtual User User { get; set; }
    }
}
