//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchSetting
    {
        public int Id { get; set; }
        public Nullable<int> BottleCounterParaId { get; set; }
        public Nullable<int> RejectCounterParaId { get; set; }
        public Nullable<int> RejCam1ParaId { get; set; }
        public Nullable<int> RejCam2ParaId { get; set; }
        public Nullable<int> MissingLabelRejeParaId { get; set; }
        public Nullable<int> GoodCounterParaId { get; set; }
    
        public virtual MachineParameter MachineParameter { get; set; }
        public virtual MachineParameter MachineParameter1 { get; set; }
        public virtual MachineParameter MachineParameter2 { get; set; }
        public virtual MachineParameter MachineParameter3 { get; set; }
        public virtual MachineParameter MachineParameter4 { get; set; }
        public virtual MachineParameter MachineParameter5 { get; set; }
    }
}
