//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchRunData
    {
        public long BatchRunDataId { get; set; }
        public Nullable<int> BatchMachineWiseId { get; set; }
        public Nullable<int> IPCParameterId { get; set; }
        public string IPCParameterValue { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<int> LoggedInUser { get; set; }
        public Nullable<int> ViewFieldId { get; set; }
    
        public virtual BatchMachineWise BatchMachineWise { get; set; }
        public virtual IPCParameter IPCParameter { get; set; }
        public virtual User User { get; set; }
        public virtual ViewField ViewField { get; set; }
    }
}
