//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.AlarmLogs = new HashSet<AlarmLog>();
            this.AlarmLogArchives = new HashSet<AlarmLogArchive>();
            this.AuditLogs = new HashSet<AuditLog>();
            this.AuditLogArchives = new HashSet<AuditLogArchive>();
            this.BatchLogs = new HashSet<BatchLog>();
            this.BatchMachineWises = new HashSet<BatchMachineWise>();
            this.LabelReconciliations = new HashSet<LabelReconciliation>();
            this.LabelRolls = new HashSet<LabelRoll>();
            this.UserLogs = new HashSet<UserLog>();
        }
    
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public Nullable<int> PackId { get; set; }
        public Nullable<System.DateTime> BatchStartDateTime { get; set; }
        public Nullable<System.DateTime> BatchEndDateTime { get; set; }
        public Nullable<int> MachineLineId { get; set; }
        public string BatchStatus { get; set; }
        public Nullable<int> BatchSize { get; set; }
        public Nullable<int> BatchFor { get; set; }
        public Nullable<int> NumberOfBottles { get; set; }
        public Nullable<int> TotalGoodBottles { get; set; }
        public Nullable<int> TotalRejectedBottles { get; set; }
        public string ProductionSpeed { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> LastBatchStartDateTime { get; set; }
        public Nullable<int> RunTime { get; set; }
        public Nullable<int> BottleCounter { get; set; }
        public string RejectedByCam1 { get; set; }
        public string RejectedByCam2 { get; set; }
        public string RejByMissingLabelSensor { get; set; }
        public string RecipeName { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public string BatchVersion { get; set; }
        public string RepackStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string BatchLatestVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmLog> AlarmLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmLogArchive> AlarmLogArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLogArchive> AuditLogArchives { get; set; }
        public virtual MachineLine MachineLine { get; set; }
        public virtual Pack Pack { get; set; }
        public virtual PickListValue PickListValue { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchLog> BatchLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMachineWise> BatchMachineWises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelReconciliation> LabelReconciliations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelRoll> LabelRolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLog> UserLogs { get; set; }
    }
}
