//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchLog
    {
        public long BatchLogId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual User User { get; set; }
    }
}
