//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottle()
        {
            this.Packs = new HashSet<Pack>();
        }
    
        public int BottleId { get; set; }
        public string BottleName { get; set; }
        public string BottleCC { get; set; }
        public Nullable<int> ContainerTypeId { get; set; }
        public string BottleHeight { get; set; }
        public string BottleDiameter { get; set; }
        public string BottleMouthOpening_ID { get; set; }
        public string BottleMouthOpening_OD { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RecordAddedSource { get; set; }
    
        public virtual PickListValue PickListValue { get; set; }
        public virtual Status Status { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pack> Packs { get; set; }
    }
}
