//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayObjectTypeColor
    {
        public int DOTColorId { get; set; }
        public string DOTColor { get; set; }
        public double Min { get; set; }
        public double Max { get; set; }
        public int DisplayObjectTypeId { get; set; }
        public int SubTypeId { get; set; }
    }
}
