//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndOfLine()
        {
            this.Packs = new HashSet<Pack>();
        }
    
        public int EndOfLineId { get; set; }
        public string EndOfLineName { get; set; }
        public string CartonLength { get; set; }
        public string CartonHeight { get; set; }
        public string CartonWidth { get; set; }
        public string CartonType { get; set; }
        public string BottleConfiguration { get; set; }
        public string MedicationLength { get; set; }
        public string MedicationWidth { get; set; }
        public string NoOfMedication { get; set; }
        public string InnerShipperBoxType { get; set; }
        public string InnerShipperBoxLength { get; set; }
        public string InnerShipperBoxWidth { get; set; }
        public string InnerShipperBoxHeight { get; set; }
        public string OuterShipperBoxLength { get; set; }
        public string OuterShipperBoxWidth { get; set; }
        public string OuterShipperBoxHeight { get; set; }
        public string InnerShipperMatrix { get; set; }
        public string OuterShipperQuantity { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RecordAddedSource { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pack> Packs { get; set; }
    }
}
