//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPCParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPCParameter()
        {
            this.BatchRunDatas = new HashSet<BatchRunData>();
            this.RecipeSettingsParameters = new HashSet<RecipeSettingsParameter>();
            this.ScreenFields = new HashSet<ScreenField>();
        }
    
        public int IPCParameterId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string IPCParameterName { get; set; }
        public Nullable<int> MachineParameterId { get; set; }
        public string IPCAddress { get; set; }
        public Nullable<bool> IsChangeInRuntime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ProtocolId { get; set; }
        public Nullable<bool> Is32Bit { get; set; }
        public string Bit32Address { get; set; }
        public Nullable<bool> IsBitWise { get; set; }
        public Nullable<int> BitWiseIndex { get; set; }
        public Nullable<bool> IsWordSwap { get; set; }
        public Nullable<bool> IsByteSwap { get; set; }
        public Nullable<bool> IsStopATIPC { get; set; }
        public Nullable<bool> IsShowAsMessageIPC { get; set; }
        public Nullable<bool> IsBatchStartRequiredIPC { get; set; }
        public Nullable<bool> IsResetOnBatchCreateIPC { get; set; }
        public Nullable<bool> IsLabelRollIPC { get; set; }
        public Nullable<int> DisableParameterIdIPC { get; set; }
        public string DisableParameterValueIPC { get; set; }
        public Nullable<bool> IsStopOnBatchStopIPC { get; set; }
        public Nullable<int> OperationTypeIPC { get; set; }
        public Nullable<decimal> OperationValueIPC { get; set; }
        public Nullable<bool> IsAlarm { get; set; }
        public Nullable<bool> IsMachineSpeed { get; set; }
        public Nullable<bool> IsRefreshMachineSettings { get; set; }
        public Nullable<bool> IsHeartBeat { get; set; }
        public Nullable<bool> IsHeartBeatSend { get; set; }
        public Nullable<int> HeartBeatFailedTime { get; set; }
        public Nullable<int> IncrementalNumber { get; set; }
        public Nullable<int> EndNumber { get; set; }
        public Nullable<int> StartNumber { get; set; }
        public Nullable<bool> IsWriteToPLC { get; set; }
        public Nullable<bool> IsIndicatorParameter { get; set; }
        public Nullable<int> IndicatorParameterId { get; set; }
        public Nullable<bool> IsGoodBottles { get; set; }
        public Nullable<bool> IsRejectBottles { get; set; }
        public Nullable<bool> IsBatchSize { get; set; }
        public Nullable<bool> IsCounterReset { get; set; }
        public Nullable<bool> IsConveyer { get; set; }
        public Nullable<bool> IsMissingLabelCounter { get; set; }
        public string NodeId { get; set; }
        public Nullable<int> AttributeId { get; set; }
        public Nullable<bool> IsTotalBottles { get; set; }
        public Nullable<bool> IsCalculated { get; set; }
        public string RecordAddedSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRunData> BatchRunDatas { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual MachineParameter MachineParameter { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeSettingsParameter> RecipeSettingsParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreenField> ScreenFields { get; set; }
        public virtual Attribute Attribute { get; set; }
    }
}
