//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDisplay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListDisplay()
        {
            this.Views = new HashSet<View>();
        }
    
        public int ListDisplayId { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<int> BorderStyle { get; set; }
        public Nullable<bool> Checkbox { get; set; }
        public string Font { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<bool> FullRowSelect { get; set; }
        public Nullable<bool> Gridlines { get; set; }
        public Nullable<bool> UseWaitCursorOnClick { get; set; }
        public Nullable<int> Activation { get; set; }
        public Nullable<int> Alignment { get; set; }
        public Nullable<int> SortingType { get; set; }
        public Nullable<bool> SortAscDesc { get; set; }
        public Nullable<bool> MultiSelect { get; set; }
        public Nullable<bool> AutoResize { get; set; }
        public Nullable<bool> Collapsible { get; set; }
        public string ListDisplayName { get; set; }
        public Nullable<int> ViewId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<View> Views { get; set; }
        public virtual View View { get; set; }
    }
}
