//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCommunication
    {
        public int MachineCommunicatonId { get; set; }
        public Nullable<int> ProtocolTypeId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> TCPIPPort { get; set; }
        public Nullable<int> PollRate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string MDBPath { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> SecurityModeId { get; set; }
        public Nullable<int> SecurityPolicyId { get; set; }
        public Nullable<int> UserIdentityId { get; set; }
        public Nullable<bool> IsConnected { get; set; }
        public string RecordAddedSource { get; set; }
        public Nullable<short> Rack { get; set; }
        public Nullable<short> Slot { get; set; }
        public Nullable<int> CpuTypeId { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual PickListValue PickListValue { get; set; }
        public virtual PickListValue PickListValue1 { get; set; }
        public virtual PickListValue PickListValue2 { get; set; }
        public virtual PickListValue PickListValue3 { get; set; }
        public virtual PickListValue PickListValue4 { get; set; }
        public virtual PickListValue PickListValue5 { get; set; }
        public virtual PickListValue PickListValue6 { get; set; }
    }
}
