//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMaster
    {
        public int MessageMasterId { get; set; }
        public int PickListValueId { get; set; }
        public string MessageText { get; set; }
        public string MessageDescription { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PickListValue PickListValue { get; set; }
    }
}
