//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pack()
        {
            this.Batches = new HashSet<Batch>();
            this.BatchArchives = new HashSet<BatchArchive>();
        }
    
        public int PackId { get; set; }
        public string PackName { get; set; }
        public Nullable<int> TabletId { get; set; }
        public Nullable<int> TabletCount { get; set; }
        public Nullable<int> BottleId { get; set; }
        public Nullable<int> CapId { get; set; }
        public Nullable<int> CottonId { get; set; }
        public string CottonLength { get; set; }
        public Nullable<int> NumberOfCottonPieces { get; set; }
        public Nullable<int> DesiccantId { get; set; }
        public Nullable<int> NumberOfDesicantPieces { get; set; }
        public Nullable<int> OutsertId { get; set; }
        public Nullable<int> LabelId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> EndOfLineId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RecordAddedSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchArchive> BatchArchives { get; set; }
        public virtual Bottle Bottle { get; set; }
        public virtual Cap Cap { get; set; }
        public virtual Cotton Cotton { get; set; }
        public virtual Desiccant Desiccant { get; set; }
        public virtual EndOfLine EndOfLine { get; set; }
        public virtual Label Label { get; set; }
        public virtual Outsert Outsert { get; set; }
        public virtual Status Status { get; set; }
        public virtual TabletDetail TabletDetail { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
