//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCParameter
    {
        public int PlcParameterId { get; set; }
        public Nullable<int> PLCId { get; set; }
        public string ParameterName { get; set; }
        public string PLCAddress { get; set; }
        public Nullable<int> DataTypeId { get; set; }
        public Nullable<bool> IsUnit { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual PickListValue PickListValue { get; set; }
        public virtual PLC PLC { get; set; }
    }
}
