//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenField
    {
        public int ScreenFieldId { get; set; }
        public Nullable<int> ScreenModuleId { get; set; }
        public Nullable<int> ScreenSectionId { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> IPCParameterId { get; set; }
        public Nullable<bool> IsDependentOn { get; set; }
        public Nullable<int> DependentFieldId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual IPCParameter IPCParameter { get; set; }
        public virtual ScreenModule ScreenModule { get; set; }
        public virtual Status Status { get; set; }
    }
}
