//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerIPCParameter
    {
        public int ServerIPCParameterId { get; set; }
        public Nullable<int> IPCParameterId { get; set; }
        public string Coils { get; set; }
        public string HoldingRegister { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsRegister { get; set; }
        public Nullable<int> ServerObjectsId { get; set; }
    }
}
