//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerObject
    {
        public int ServerObjectsId { get; set; }
        public Nullable<int> ProtocolTypeId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> TCPIPPort { get; set; }
        public Nullable<int> PollRate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string MDBPath { get; set; }
    }
}
