//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabletDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabletDetail()
        {
            this.Packs = new HashSet<Pack>();
        }
    
        public int TabletDetailsId { get; set; }
        public string TabletName { get; set; }
        public string TabletStrength { get; set; }
        public Nullable<int> TabletTypeId { get; set; }
        public Nullable<int> TabletCharOneId { get; set; }
        public Nullable<int> TabletCharTwoId { get; set; }
        public Nullable<int> TabletShapeId { get; set; }
        public string TabletLength { get; set; }
        public string TabletThickness { get; set; }
        public string TabletWidth { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RecordAddedSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pack> Packs { get; set; }
        public virtual PickListValue PickListValue { get; set; }
        public virtual PickListValue PickListValue1 { get; set; }
        public virtual PickListValue PickListValue2 { get; set; }
        public virtual Status Status { get; set; }
    }
}
