//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogArchive
    {
        public long UserLogArchiveId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
