//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVC.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ViewField()
        {
            this.ViewFieldAccesses = new HashSet<ViewFieldAccess>();
            this.ViewFieldAuthentications = new HashSet<ViewFieldAuthentication>();
            this.BatchRunDatas = new HashSet<BatchRunData>();
        }
    
        public int ViewField1 { get; set; }
        public Nullable<int> ViewsId { get; set; }
        public string ViewFieldName { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> MachineParameterId { get; set; }
        public Nullable<bool> IsPopUpRequired { get; set; }
        public Nullable<bool> IsCommentRequired { get; set; }
        public Nullable<bool> IsAuthenticationRequired { get; set; }
        public Nullable<int> ModuleId { get; set; }
    
        public virtual MachineParameter MachineParameter { get; set; }
        public virtual Module Module { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual View View { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewFieldAccess> ViewFieldAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewFieldAuthentication> ViewFieldAuthentications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRunData> BatchRunDatas { get; set; }
    }
}
